docs-website:
  - changed-files:
    - any-glob-to-any-file:
      - website/docs/**/*
packages/components:
  - changed-files:
    - any-glob-to-any-file:
      - packages/components/**/*
packages/flight-icons:
  - changed-files:
    - any-glob-to-any-file:
      - packages/flight-icons/**/*
packages/tokens:
  - changed-files:
    - any-glob-to-any-file:
      - packages/tokens/**/*
packages/mcp:
  - changed-files:
    - any-glob-to-any-file:
      - packages/mcp/**/*
showcase:
  - changed-files:
    - any-glob-to-any-file:
      - showcase/**/*