packages:
  - 'packages/**'
  - showcase
  - website

overrides:
  '@babel/plugin-transform-modules-systemjs': '7.29.4'
  '@glimmer/component': '^2.0.0'
  '@xmldom/xmldom': '0.9.10'
  'ajv@6': '6.14.0'
  basic-ftp: '5.3.1'
  'brace-expansion@1': '1.1.13'
  'brace-expansion@2': '2.0.3'
  'brace-expansion@5': '5.0.6'
  fast-uri: '3.1.2'
  flatted: '3.4.4'
  follow-redirects: '1.16.0'
  'form-data': '4.0.6'
  ember-composable-helpers: 'npm:@nullvoxpopuli/ember-composable-helpers@^5.2.11'
  handlebars: '4.7.9'
  'js-yaml@3': '3.14.2'
  'js-yaml@4': '4.1.1'
  linkify-it: '5.0.1'
  markdown-it: '14.1.1'
  mdast-util-to-hast: '13.2.1'
  "minimatch@<3.0.5": '3.1.2'
  'path-to-regexp@0': '0.1.13'
  'path-to-regexp@8': '8.4.2'
  qs: '6.15.2'
  systeminformation: '5.31.6'
  tmp: '0.2.7'
  underscore: '1.13.8'
  'yaml@1': '1.10.3'

patchedDependencies:
  broccoli-asset-rewrite: patches/broccoli-asset-rewrite.patch
  'ember-app-scheduler@7.0.1': patches/ember-app-scheduler@7.0.1.patch

onlyBuiltDependencies:
  - '@carbon/charts'
  - '@carbon/colors'
  - '@carbon/grid'
  - '@carbon/icons'
  - '@carbon/layout'
  - '@carbon/motion'
  - '@carbon/themes'
  - '@carbon/type'
  - '@carbon/utils-position'
  - '@parcel/watcher'
  - '@percy/core'
  - core-js
  - esbuild