export const carbonMap: Record<string, () => Promise<{ default: unknown }>> = {
  'accessibility--alt/16': () =>
    import('@carbon/icons/es/accessibility--alt/16.js'),
  'accessibility--alt/24': () =>
    import('@carbon/icons/es/accessibility--alt/24.js'),
  'activity/16': () => import('@carbon/icons/es/activity/16.js'),
  'activity/24': () => import('@carbon/icons/es/activity/24.js'),
  'add/16': () => import('@carbon/icons/es/add/16.js'),
  'add/24': () => import('@carbon/icons/es/add/24.js'),
  'add--alt/16': () => import('@carbon/icons/es/add--alt/16.js'),
  'add--alt/24': () => import('@carbon/icons/es/add--alt/24.js'),
  'add--filled/16': () => import('@carbon/icons/es/add--filled/16.js'),
  'add--filled/24': () => import('@carbon/icons/es/add--filled/24.js'),
  'ai-label/16': () => import('@carbon/icons/es/ai-label/16.js'),
  'ai-label/24': () => import('@carbon/icons/es/ai-label/24.js'),
  'api/16': () => import('@carbon/icons/es/api/16.js'),
  'api/24': () => import('@carbon/icons/es/api/24.js'),
  'arrow--down/16': () => import('@carbon/icons/es/arrow--down/16.js'),
  'arrow--down/24': () => import('@carbon/icons/es/arrow--down/24.js'),
  'arrow--down-left/16': () =>
    import('@carbon/icons/es/arrow--down-left/16.js'),
  'arrow--down-left/24': () =>
    import('@carbon/icons/es/arrow--down-left/24.js'),
  'arrow--down-right/16': () =>
    import('@carbon/icons/es/arrow--down-right/16.js'),
  'arrow--down-right/24': () =>
    import('@carbon/icons/es/arrow--down-right/24.js'),
  'arrow--left/16': () => import('@carbon/icons/es/arrow--left/16.js'),
  'arrow--left/24': () => import('@carbon/icons/es/arrow--left/24.js'),
  'arrow--right/16': () => import('@carbon/icons/es/arrow--right/16.js'),
  'arrow--right/24': () => import('@carbon/icons/es/arrow--right/24.js'),
  'arrow--up/16': () => import('@carbon/icons/es/arrow--up/16.js'),
  'arrow--up/24': () => import('@carbon/icons/es/arrow--up/24.js'),
  'arrow--up-left/16': () => import('@carbon/icons/es/arrow--up-left/16.js'),
  'arrow--up-left/24': () => import('@carbon/icons/es/arrow--up-left/24.js'),
  'arrow--up-right/16': () => import('@carbon/icons/es/arrow--up-right/16.js'),
  'arrow--up-right/24': () => import('@carbon/icons/es/arrow--up-right/24.js'),
  'arrows--horizontal/16': () =>
    import('@carbon/icons/es/arrows--horizontal/16.js'),
  'arrows--horizontal/24': () =>
    import('@carbon/icons/es/arrows--horizontal/24.js'),
  'arrows--vertical/16': () =>
    import('@carbon/icons/es/arrows--vertical/16.js'),
  'arrows--vertical/24': () =>
    import('@carbon/icons/es/arrows--vertical/24.js'),
  'assignment-action--usage/16': () =>
    import('@carbon/icons/es/assignment-action--usage/16.js'),
  'assignment-action--usage/24': () =>
    import('@carbon/icons/es/assignment-action--usage/24.js'),
  'async/16': () => import('@carbon/icons/es/async/16.js'),
  'async/24': () => import('@carbon/icons/es/async/24.js'),
  'at/16': () => import('@carbon/icons/es/at/16.js'),
  'at/24': () => import('@carbon/icons/es/at/24.js'),
  'attachment/16': () => import('@carbon/icons/es/attachment/16.js'),
  'attachment/24': () => import('@carbon/icons/es/attachment/24.js'),
  'audio-console/16': () => import('@carbon/icons/es/audio-console/16.js'),
  'audio-console/24': () => import('@carbon/icons/es/audio-console/24.js'),
  'bare-metal-server/16': () =>
    import('@carbon/icons/es/bare-metal-server/16.js'),
  'bare-metal-server/24': () =>
    import('@carbon/icons/es/bare-metal-server/24.js'),
  'battery--charging/16': () =>
    import('@carbon/icons/es/battery--charging/16.js'),
  'battery--charging/24': () =>
    import('@carbon/icons/es/battery--charging/24.js'),
  'battery--empty/16': () => import('@carbon/icons/es/battery--empty/16.js'),
  'battery--empty/24': () => import('@carbon/icons/es/battery--empty/24.js'),
  'blog/16': () => import('@carbon/icons/es/blog/16.js'),
  'blog/24': () => import('@carbon/icons/es/blog/24.js'),
  'book/16': () => import('@carbon/icons/es/book/16.js'),
  'book/24': () => import('@carbon/icons/es/book/24.js'),
  'bookmark/16': () => import('@carbon/icons/es/bookmark/16.js'),
  'bookmark/24': () => import('@carbon/icons/es/bookmark/24.js'),
  'bookmark--add/16': () => import('@carbon/icons/es/bookmark--add/16.js'),
  'bookmark--add/24': () => import('@carbon/icons/es/bookmark--add/24.js'),
  'bookmark--filled/16': () =>
    import('@carbon/icons/es/bookmark--filled/16.js'),
  'bookmark--filled/24': () =>
    import('@carbon/icons/es/bookmark--filled/24.js'),
  'bot/16': () => import('@carbon/icons/es/bot/16.js'),
  'bot/24': () => import('@carbon/icons/es/bot/24.js'),
  'box/16': () => import('@carbon/icons/es/box/16.js'),
  'box/24': () => import('@carbon/icons/es/box/24.js'),
  'branch/16': () => import('@carbon/icons/es/branch/16.js'),
  'branch/24': () => import('@carbon/icons/es/branch/24.js'),
  'building/16': () => import('@carbon/icons/es/building/16.js'),
  'building/24': () => import('@carbon/icons/es/building/24.js'),
  'calendar/16': () => import('@carbon/icons/es/calendar/16.js'),
  'calendar/24': () => import('@carbon/icons/es/calendar/24.js'),
  'camera/16': () => import('@carbon/icons/es/camera/16.js'),
  'camera/24': () => import('@carbon/icons/es/camera/24.js'),
  'center--circle/16': () => import('@carbon/icons/es/center--circle/16.js'),
  'center--circle/24': () => import('@carbon/icons/es/center--circle/24.js'),
  'character-patterns/16': () =>
    import('@carbon/icons/es/character-patterns/16.js'),
  'character-patterns/24': () =>
    import('@carbon/icons/es/character-patterns/24.js'),
  'chart--column/16': () => import('@carbon/icons/es/chart--column/16.js'),
  'chart--column/24': () => import('@carbon/icons/es/chart--column/24.js'),
  'chart--line/16': () => import('@carbon/icons/es/chart--line/16.js'),
  'chart--line/24': () => import('@carbon/icons/es/chart--line/24.js'),
  'chart--pie/16': () => import('@carbon/icons/es/chart--pie/16.js'),
  'chart--pie/24': () => import('@carbon/icons/es/chart--pie/24.js'),
  'chat/16': () => import('@carbon/icons/es/chat/16.js'),
  'chat/24': () => import('@carbon/icons/es/chat/24.js'),
  'checkbox--checked/16': () =>
    import('@carbon/icons/es/checkbox--checked/16.js'),
  'checkbox--checked/24': () =>
    import('@carbon/icons/es/checkbox--checked/24.js'),
  'checkbox--checked--filled/16': () =>
    import('@carbon/icons/es/checkbox--checked--filled/16.js'),
  'checkbox--checked--filled/24': () =>
    import('@carbon/icons/es/checkbox--checked--filled/24.js'),
  'checkmark/16': () => import('@carbon/icons/es/checkmark/16.js'),
  'checkmark/24': () => import('@carbon/icons/es/checkmark/24.js'),
  'checkmark--filled/16': () =>
    import('@carbon/icons/es/checkmark--filled/16.js'),
  'checkmark--filled/24': () =>
    import('@carbon/icons/es/checkmark--filled/24.js'),
  'checkmark--outline/16': () =>
    import('@carbon/icons/es/checkmark--outline/16.js'),
  'checkmark--outline/24': () =>
    import('@carbon/icons/es/checkmark--outline/24.js'),
  'chemistry/16': () => import('@carbon/icons/es/chemistry/16.js'),
  'chemistry/24': () => import('@carbon/icons/es/chemistry/24.js'),
  'chevron--down/16': () => import('@carbon/icons/es/chevron--down/16.js'),
  'chevron--down/24': () => import('@carbon/icons/es/chevron--down/24.js'),
  'chevron--left/16': () => import('@carbon/icons/es/chevron--left/16.js'),
  'chevron--left/24': () => import('@carbon/icons/es/chevron--left/24.js'),
  'chevron--right/16': () => import('@carbon/icons/es/chevron--right/16.js'),
  'chevron--right/24': () => import('@carbon/icons/es/chevron--right/24.js'),
  'chevron--sort/16': () => import('@carbon/icons/es/chevron--sort/16.js'),
  'chevron--sort/24': () => import('@carbon/icons/es/chevron--sort/24.js'),
  'chevron--up/16': () => import('@carbon/icons/es/chevron--up/16.js'),
  'chevron--up/24': () => import('@carbon/icons/es/chevron--up/24.js'),
  'chip/16': () => import('@carbon/icons/es/chip/16.js'),
  'chip/24': () => import('@carbon/icons/es/chip/24.js'),
  'circle--solid/16': () => import('@carbon/icons/es/circle--solid/16.js'),
  'circle--solid/24': () => import('@carbon/icons/es/circle--solid/24.js'),
  'circle--filled/16': () => import('@carbon/icons/es/circle--filled/16.js'),
  'circle--filled/24': () => import('@carbon/icons/es/circle--filled/24.js'),
  'circle--outline/16': () => import('@carbon/icons/es/circle--outline/16.js'),
  'circle--outline/24': () => import('@carbon/icons/es/circle--outline/24.js'),
  'close/16': () => import('@carbon/icons/es/close/16.js'),
  'close/24': () => import('@carbon/icons/es/close/24.js'),
  'close--filled/16': () => import('@carbon/icons/es/close--filled/16.js'),
  'close--filled/24': () => import('@carbon/icons/es/close--filled/24.js'),
  'close--outline/16': () => import('@carbon/icons/es/close--outline/16.js'),
  'close--outline/24': () => import('@carbon/icons/es/close--outline/24.js'),
  'closed-caption/16': () => import('@carbon/icons/es/closed-caption/16.js'),
  'closed-caption/24': () => import('@carbon/icons/es/closed-caption/24.js'),
  'cloud/16': () => import('@carbon/icons/es/cloud/16.js'),
  'cloud/24': () => import('@carbon/icons/es/cloud/24.js'),
  'cloud--download/16': () => import('@carbon/icons/es/cloud--download/16.js'),
  'cloud--download/24': () => import('@carbon/icons/es/cloud--download/24.js'),
  'cloud--logging/16': () => import('@carbon/icons/es/cloud--logging/16.js'),
  'cloud--logging/24': () => import('@carbon/icons/es/cloud--logging/24.js'),
  'cloud--offline/16': () => import('@carbon/icons/es/cloud--offline/16.js'),
  'cloud--offline/24': () => import('@carbon/icons/es/cloud--offline/24.js'),
  'cloud--upload/16': () => import('@carbon/icons/es/cloud--upload/16.js'),
  'cloud--upload/24': () => import('@carbon/icons/es/cloud--upload/24.js'),
  'code/16': () => import('@carbon/icons/es/code/16.js'),
  'code/24': () => import('@carbon/icons/es/code/24.js'),
  'commit/16': () => import('@carbon/icons/es/commit/16.js'),
  'commit/24': () => import('@carbon/icons/es/commit/24.js'),
  'connection-signal/16': () =>
    import('@carbon/icons/es/connection-signal/16.js'),
  'connection-signal/24': () =>
    import('@carbon/icons/es/connection-signal/24.js'),
  'container--image/16': () =>
    import('@carbon/icons/es/container--image/16.js'),
  'container--image/24': () =>
    import('@carbon/icons/es/container--image/24.js'),
  'contrast/16': () => import('@carbon/icons/es/contrast/16.js'),
  'contrast/24': () => import('@carbon/icons/es/contrast/24.js'),
  'copy/16': () => import('@carbon/icons/es/copy/16.js'),
  'copy/24': () => import('@carbon/icons/es/copy/24.js'),
  'crop/16': () => import('@carbon/icons/es/crop/16.js'),
  'crop/24': () => import('@carbon/icons/es/crop/24.js'),
  'cube/16': () => import('@carbon/icons/es/cube/16.js'),
  'cube/24': () => import('@carbon/icons/es/cube/24.js'),
  'currency--dollar/16': () =>
    import('@carbon/icons/es/currency--dollar/16.js'),
  'currency--dollar/24': () =>
    import('@carbon/icons/es/currency--dollar/24.js'),
  'cursor--1/16': () => import('@carbon/icons/es/cursor--1/16.js'),
  'cursor--1/24': () => import('@carbon/icons/es/cursor--1/24.js'),
  'cut/16': () => import('@carbon/icons/es/cut/16.js'),
  'cut/24': () => import('@carbon/icons/es/cut/24.js'),
  'dashboard/16': () => import('@carbon/icons/es/dashboard/16.js'),
  'dashboard/24': () => import('@carbon/icons/es/dashboard/24.js'),
  'data--base/16': () => import('@carbon/icons/es/data--base/16.js'),
  'data--base/24': () => import('@carbon/icons/es/data--base/24.js'),
  'debug/16': () => import('@carbon/icons/es/debug/16.js'),
  'debug/24': () => import('@carbon/icons/es/debug/24.js'),
  'delete/16': () => import('@carbon/icons/es/delete/16.js'),
  'delete/24': () => import('@carbon/icons/es/delete/24.js'),
  'delivery-truck/16': () => import('@carbon/icons/es/delivery-truck/16.js'),
  'delivery-truck/24': () => import('@carbon/icons/es/delivery-truck/24.js'),
  'diamond--outline/16': () =>
    import('@carbon/icons/es/diamond--outline/16.js'),
  'diamond--outline/24': () =>
    import('@carbon/icons/es/diamond--outline/24.js'),
  'document/16': () => import('@carbon/icons/es/document/16.js'),
  'document/24': () => import('@carbon/icons/es/document/24.js'),
  'document--add/16': () => import('@carbon/icons/es/document--add/16.js'),
  'document--add/24': () => import('@carbon/icons/es/document--add/24.js'),
  'document--blank/16': () => import('@carbon/icons/es/document--blank/16.js'),
  'document--blank/24': () => import('@carbon/icons/es/document--blank/24.js'),
  'document--download/16': () =>
    import('@carbon/icons/es/document--download/16.js'),
  'document--download/24': () =>
    import('@carbon/icons/es/document--download/24.js'),
  'document--multiple-02/16': () =>
    import('@carbon/icons/es/document--multiple-02/16.js'),
  'document--multiple-02/24': () =>
    import('@carbon/icons/es/document--multiple-02/24.js'),
  'document--subtract/16': () =>
    import('@carbon/icons/es/document--subtract/16.js'),
  'document--subtract/24': () =>
    import('@carbon/icons/es/document--subtract/24.js'),
  'document--tasks/16': () => import('@carbon/icons/es/document--tasks/16.js'),
  'document--tasks/24': () => import('@carbon/icons/es/document--tasks/24.js'),
  'dot-mark/16': () => import('@carbon/icons/es/dot-mark/16.js'),
  'dot-mark/24': () => import('@carbon/icons/es/dot-mark/24.js'),
  'down-to-bottom/16': () => import('@carbon/icons/es/down-to-bottom/16.js'),
  'down-to-bottom/24': () => import('@carbon/icons/es/down-to-bottom/24.js'),
  'download/16': () => import('@carbon/icons/es/download/16.js'),
  'download/24': () => import('@carbon/icons/es/download/24.js'),
  'edit/16': () => import('@carbon/icons/es/edit/16.js'),
  'edit/24': () => import('@carbon/icons/es/edit/24.js'),
  'education/16': () => import('@carbon/icons/es/education/16.js'),
  'education/24': () => import('@carbon/icons/es/education/24.js'),
  'email/16': () => import('@carbon/icons/es/email/16.js'),
  'email/24': () => import('@carbon/icons/es/email/24.js'),
  'enterprise/16': () => import('@carbon/icons/es/enterprise/16.js'),
  'enterprise/24': () => import('@carbon/icons/es/enterprise/24.js'),
  'error/16': () => import('@carbon/icons/es/error/16.js'),
  'error/24': () => import('@carbon/icons/es/error/24.js'),
  'event/16': () => import('@carbon/icons/es/event/16.js'),
  'event/24': () => import('@carbon/icons/es/event/24.js'),
  'explore/16': () => import('@carbon/icons/es/explore/16.js'),
  'explore/24': () => import('@carbon/icons/es/explore/24.js'),
  'face--neutral/16': () => import('@carbon/icons/es/face--neutral/16.js'),
  'face--neutral/24': () => import('@carbon/icons/es/face--neutral/24.js'),
  'face--satisfied/16': () => import('@carbon/icons/es/face--satisfied/16.js'),
  'face--satisfied/24': () => import('@carbon/icons/es/face--satisfied/24.js'),
  'favorite/16': () => import('@carbon/icons/es/favorite/16.js'),
  'favorite/24': () => import('@carbon/icons/es/favorite/24.js'),
  'favorite--filled/16': () =>
    import('@carbon/icons/es/favorite--filled/16.js'),
  'favorite--filled/24': () =>
    import('@carbon/icons/es/favorite--filled/24.js'),
  'filter/16': () => import('@carbon/icons/es/filter/16.js'),
  'filter/24': () => import('@carbon/icons/es/filter/24.js'),
  'finance/16': () => import('@carbon/icons/es/finance/16.js'),
  'finance/24': () => import('@carbon/icons/es/finance/24.js'),
  'fingerprint-recognition/16': () =>
    import('@carbon/icons/es/fingerprint-recognition/16.js'),
  'fingerprint-recognition/24': () =>
    import('@carbon/icons/es/fingerprint-recognition/24.js'),
  'flag/16': () => import('@carbon/icons/es/flag/16.js'),
  'flag/24': () => import('@carbon/icons/es/flag/24.js'),
  'flash/16': () => import('@carbon/icons/es/flash/16.js'),
  'flash/24': () => import('@carbon/icons/es/flash/24.js'),
  'flash--off/16': () => import('@carbon/icons/es/flash--off/16.js'),
  'flash--off/24': () => import('@carbon/icons/es/flash--off/24.js'),
  'folder/16': () => import('@carbon/icons/es/folder/16.js'),
  'folder/24': () => import('@carbon/icons/es/folder/24.js'),
  'folder--add/16': () => import('@carbon/icons/es/folder--add/16.js'),
  'folder--add/24': () => import('@carbon/icons/es/folder--add/24.js'),
  'folder--shared/16': () => import('@carbon/icons/es/folder--shared/16.js'),
  'folder--shared/24': () => import('@carbon/icons/es/folder--shared/24.js'),
  'forum/16': () => import('@carbon/icons/es/forum/16.js'),
  'forum/24': () => import('@carbon/icons/es/forum/24.js'),
  'gateway/16': () => import('@carbon/icons/es/gateway/16.js'),
  'gateway/24': () => import('@carbon/icons/es/gateway/24.js'),
  'gift/16': () => import('@carbon/icons/es/gift/16.js'),
  'gift/24': () => import('@carbon/icons/es/gift/24.js'),
  'grid/16': () => import('@carbon/icons/es/grid/16.js'),
  'grid/24': () => import('@carbon/icons/es/grid/24.js'),
  'growth/16': () => import('@carbon/icons/es/growth/16.js'),
  'growth/24': () => import('@carbon/icons/es/growth/24.js'),
  'hashtag/16': () => import('@carbon/icons/es/hashtag/16.js'),
  'hashtag/24': () => import('@carbon/icons/es/hashtag/24.js'),
  'headphones/16': () => import('@carbon/icons/es/headphones/16.js'),
  'headphones/24': () => import('@carbon/icons/es/headphones/24.js'),
  'help/16': () => import('@carbon/icons/es/help/16.js'),
  'help/24': () => import('@carbon/icons/es/help/24.js'),
  'hexagon--outline/16': () =>
    import('@carbon/icons/es/hexagon--outline/16.js'),
  'hexagon--outline/24': () =>
    import('@carbon/icons/es/hexagon--outline/24.js'),
  'hexagon--solid/16': () => import('@carbon/icons/es/hexagon--solid/16.js'),
  'hexagon--solid/24': () => import('@carbon/icons/es/hexagon--solid/24.js'),
  'hourglass/16': () => import('@carbon/icons/es/hourglass/16.js'),
  'hourglass/24': () => import('@carbon/icons/es/hourglass/24.js'),
  'idea/16': () => import('@carbon/icons/es/idea/16.js'),
  'idea/24': () => import('@carbon/icons/es/idea/24.js'),
  'identification/16': () => import('@carbon/icons/es/identification/16.js'),
  'identification/24': () => import('@carbon/icons/es/identification/24.js'),
  'image/16': () => import('@carbon/icons/es/image/16.js'),
  'image/24': () => import('@carbon/icons/es/image/24.js'),
  'information/16': () => import('@carbon/icons/es/information/16.js'),
  'information/24': () => import('@carbon/icons/es/information/24.js'),
  'information--filled/16': () =>
    import('@carbon/icons/es/information--filled/16.js'),
  'information--filled/24': () =>
    import('@carbon/icons/es/information--filled/24.js'),
  'jump-link/16': () => import('@carbon/icons/es/jump-link/16.js'),
  'jump-link/24': () => import('@carbon/icons/es/jump-link/24.js'),
  'launch/16': () => import('@carbon/icons/es/launch/16.js'),
  'launch/24': () => import('@carbon/icons/es/launch/24.js'),
  'layers/16': () => import('@carbon/icons/es/layers/16.js'),
  'layers/24': () => import('@carbon/icons/es/layers/24.js'),
  'lifesaver/16': () => import('@carbon/icons/es/lifesaver/16.js'),
  'lifesaver/24': () => import('@carbon/icons/es/lifesaver/24.js'),
  'link/16': () => import('@carbon/icons/es/link/16.js'),
  'link/24': () => import('@carbon/icons/es/link/24.js'),
  'list/16': () => import('@carbon/icons/es/list/16.js'),
  'list/24': () => import('@carbon/icons/es/list/24.js'),
  'load-balancer--classic/16': () =>
    import('@carbon/icons/es/load-balancer--classic/16.js'),
  'load-balancer--classic/24': () =>
    import('@carbon/icons/es/load-balancer--classic/24.js'),
  'location/16': () => import('@carbon/icons/es/location/16.js'),
  'location/24': () => import('@carbon/icons/es/location/24.js'),
  'location--current/16': () =>
    import('@carbon/icons/es/location--current/16.js'),
  'location--current/24': () =>
    import('@carbon/icons/es/location--current/24.js'),
  'locked/16': () => import('@carbon/icons/es/locked/16.js'),
  'locked/24': () => import('@carbon/icons/es/locked/24.js'),
  'login/16': () => import('@carbon/icons/es/login/16.js'),
  'login/24': () => import('@carbon/icons/es/login/24.js'),
  'logout/16': () => import('@carbon/icons/es/logout/16.js'),
  'logout/24': () => import('@carbon/icons/es/logout/24.js'),
  'mac--command/16': () => import('@carbon/icons/es/mac--command/16.js'),
  'mac--command/24': () => import('@carbon/icons/es/mac--command/24.js'),
  'magic-wand/16': () => import('@carbon/icons/es/magic-wand/16.js'),
  'magic-wand/24': () => import('@carbon/icons/es/magic-wand/24.js'),
  'map/16': () => import('@carbon/icons/es/map/16.js'),
  'map/24': () => import('@carbon/icons/es/map/24.js'),
  'marginal/16': () => import('@carbon/icons/es/marginal/16.js'),
  'marginal/24': () => import('@carbon/icons/es/marginal/24.js'),
  'maximize/16': () => import('@carbon/icons/es/maximize/16.js'),
  'maximize/24': () => import('@carbon/icons/es/maximize/24.js'),
  'media-cast/16': () => import('@carbon/icons/es/media-cast/16.js'),
  'media-cast/24': () => import('@carbon/icons/es/media-cast/24.js'),
  'menu/16': () => import('@carbon/icons/es/menu/16.js'),
  'menu/24': () => import('@carbon/icons/es/menu/24.js'),
  'merge/16': () => import('@carbon/icons/es/merge/16.js'),
  'merge/24': () => import('@carbon/icons/es/merge/24.js'),
  'microphone/16': () => import('@carbon/icons/es/microphone/16.js'),
  'microphone/24': () => import('@carbon/icons/es/microphone/24.js'),
  'microphone--off/16': () => import('@carbon/icons/es/microphone--off/16.js'),
  'microphone--off/24': () => import('@carbon/icons/es/microphone--off/24.js'),
  'migrate--alt/16': () => import('@carbon/icons/es/migrate--alt/16.js'),
  'migrate--alt/24': () => import('@carbon/icons/es/migrate--alt/24.js'),
  'minimize/16': () => import('@carbon/icons/es/minimize/16.js'),
  'minimize/24': () => import('@carbon/icons/es/minimize/24.js'),
  'mobile/16': () => import('@carbon/icons/es/mobile/16.js'),
  'mobile/24': () => import('@carbon/icons/es/mobile/24.js'),
  'model/16': () => import('@carbon/icons/es/model/16.js'),
  'model/24': () => import('@carbon/icons/es/model/24.js'),
  'moon/16': () => import('@carbon/icons/es/moon/16.js'),
  'moon/24': () => import('@carbon/icons/es/moon/24.js'),
  'move/16': () => import('@carbon/icons/es/move/16.js'),
  'move/24': () => import('@carbon/icons/es/move/24.js'),
  'music/16': () => import('@carbon/icons/es/music/16.js'),
  'music/24': () => import('@carbon/icons/es/music/24.js'),
  'navaid--military/16': () =>
    import('@carbon/icons/es/navaid--military/16.js'),
  'navaid--military/24': () =>
    import('@carbon/icons/es/navaid--military/24.js'),
  'network--2/16': () => import('@carbon/icons/es/network--2/16.js'),
  'network--2/24': () => import('@carbon/icons/es/network--2/24.js'),
  'network--3/16': () => import('@carbon/icons/es/network--3/16.js'),
  'network--3/24': () => import('@carbon/icons/es/network--3/24.js'),
  'network--4/16': () => import('@carbon/icons/es/network--4/16.js'),
  'network--4/24': () => import('@carbon/icons/es/network--4/24.js'),
  'next--outline/16': () => import('@carbon/icons/es/next--outline/16.js'),
  'next--outline/24': () => import('@carbon/icons/es/next--outline/24.js'),
  'notification/16': () => import('@carbon/icons/es/notification/16.js'),
  'notification/24': () => import('@carbon/icons/es/notification/24.js'),
  'notification--new/16': () =>
    import('@carbon/icons/es/notification--new/16.js'),
  'notification--new/24': () =>
    import('@carbon/icons/es/notification--new/24.js'),
  'notification--off/16': () =>
    import('@carbon/icons/es/notification--off/16.js'),
  'notification--off/24': () =>
    import('@carbon/icons/es/notification--off/24.js'),
  'open-panel--left/16': () =>
    import('@carbon/icons/es/open-panel--left/16.js'),
  'open-panel--left/24': () =>
    import('@carbon/icons/es/open-panel--left/24.js'),
  'overflow-menu--horizontal/16': () =>
    import('@carbon/icons/es/overflow-menu--horizontal/16.js'),
  'overflow-menu--horizontal/24': () =>
    import('@carbon/icons/es/overflow-menu--horizontal/24.js'),
  'overflow-menu--vertical/16': () =>
    import('@carbon/icons/es/overflow-menu--vertical/16.js'),
  'overflow-menu--vertical/24': () =>
    import('@carbon/icons/es/overflow-menu--vertical/24.js'),
  'page--first/16': () => import('@carbon/icons/es/page--first/16.js'),
  'page--first/24': () => import('@carbon/icons/es/page--first/24.js'),
  'page--last/16': () => import('@carbon/icons/es/page--last/16.js'),
  'page--last/24': () => import('@carbon/icons/es/page--last/24.js'),
  'partnership/16': () => import('@carbon/icons/es/partnership/16.js'),
  'partnership/24': () => import('@carbon/icons/es/partnership/24.js'),
  'password/16': () => import('@carbon/icons/es/password/16.js'),
  'password/24': () => import('@carbon/icons/es/password/24.js'),
  'pause/16': () => import('@carbon/icons/es/pause/16.js'),
  'pause/24': () => import('@carbon/icons/es/pause/24.js'),
  'pen--fountain/16': () => import('@carbon/icons/es/pen--fountain/16.js'),
  'pen--fountain/24': () => import('@carbon/icons/es/pen--fountain/24.js'),
  'phone/16': () => import('@carbon/icons/es/phone/16.js'),
  'phone/24': () => import('@carbon/icons/es/phone/24.js'),
  'phone--off/16': () => import('@carbon/icons/es/phone--off/16.js'),
  'phone--off/24': () => import('@carbon/icons/es/phone--off/24.js'),
  'phone--voice/16': () => import('@carbon/icons/es/phone--voice/16.js'),
  'phone--voice/24': () => import('@carbon/icons/es/phone--voice/24.js'),
  'pin/16': () => import('@carbon/icons/es/pin/16.js'),
  'pin/24': () => import('@carbon/icons/es/pin/24.js'),
  'pipelines/16': () => import('@carbon/icons/es/pipelines/16.js'),
  'pipelines/24': () => import('@carbon/icons/es/pipelines/24.js'),
  'play/16': () => import('@carbon/icons/es/play/16.js'),
  'play/24': () => import('@carbon/icons/es/play/24.js'),
  'play--outline/16': () => import('@carbon/icons/es/play--outline/16.js'),
  'play--outline/24': () => import('@carbon/icons/es/play--outline/24.js'),
  'plug/16': () => import('@carbon/icons/es/plug/16.js'),
  'plug/24': () => import('@carbon/icons/es/plug/24.js'),
  'policy/16': () => import('@carbon/icons/es/policy/16.js'),
  'policy/24': () => import('@carbon/icons/es/policy/24.js'),
  'port--input/16': () => import('@carbon/icons/es/port--input/16.js'),
  'port--input/24': () => import('@carbon/icons/es/port--input/24.js'),
  'port--output/16': () => import('@carbon/icons/es/port--output/16.js'),
  'port--output/24': () => import('@carbon/icons/es/port--output/24.js'),
  'portfolio/16': () => import('@carbon/icons/es/portfolio/16.js'),
  'portfolio/24': () => import('@carbon/icons/es/portfolio/24.js'),
  'power/16': () => import('@carbon/icons/es/power/16.js'),
  'power/24': () => import('@carbon/icons/es/power/24.js'),
  'previous--outline/16': () =>
    import('@carbon/icons/es/previous--outline/16.js'),
  'previous--outline/24': () =>
    import('@carbon/icons/es/previous--outline/24.js'),
  'printer/16': () => import('@carbon/icons/es/printer/16.js'),
  'printer/24': () => import('@carbon/icons/es/printer/24.js'),
  'pull-request/16': () => import('@carbon/icons/es/pull-request/16.js'),
  'pull-request/24': () => import('@carbon/icons/es/pull-request/24.js'),
  'purchase/16': () => import('@carbon/icons/es/purchase/16.js'),
  'purchase/24': () => import('@carbon/icons/es/purchase/24.js'),
  'rain-drop/16': () => import('@carbon/icons/es/rain-drop/16.js'),
  'rain-drop/24': () => import('@carbon/icons/es/rain-drop/24.js'),
  'recently-viewed/16': () => import('@carbon/icons/es/recently-viewed/16.js'),
  'recently-viewed/24': () => import('@carbon/icons/es/recently-viewed/24.js'),
  'recommend/16': () => import('@carbon/icons/es/recommend/16.js'),
  'recommend/24': () => import('@carbon/icons/es/recommend/24.js'),
  'recording/16': () => import('@carbon/icons/es/recording/16.js'),
  'recording/24': () => import('@carbon/icons/es/recording/24.js'),
  'renew/16': () => import('@carbon/icons/es/renew/16.js'),
  'renew/24': () => import('@carbon/icons/es/renew/24.js'),
  'repeat/16': () => import('@carbon/icons/es/repeat/16.js'),
  'repeat/24': () => import('@carbon/icons/es/repeat/24.js'),
  'replicate/16': () => import('@carbon/icons/es/replicate/16.js'),
  'replicate/24': () => import('@carbon/icons/es/replicate/24.js'),
  'report/16': () => import('@carbon/icons/es/report/16.js'),
  'report/24': () => import('@carbon/icons/es/report/24.js'),
  'restart/16': () => import('@carbon/icons/es/restart/16.js'),
  'restart/24': () => import('@carbon/icons/es/restart/24.js'),
  'rocket/16': () => import('@carbon/icons/es/rocket/16.js'),
  'rocket/24': () => import('@carbon/icons/es/rocket/24.js'),
  'rotate/16': () => import('@carbon/icons/es/rotate/16.js'),
  'rotate/24': () => import('@carbon/icons/es/rotate/24.js'),
  'rss/16': () => import('@carbon/icons/es/rss/16.js'),
  'rss/24': () => import('@carbon/icons/es/rss/24.js'),
  'rule/16': () => import('@carbon/icons/es/rule/16.js'),
  'rule/24': () => import('@carbon/icons/es/rule/24.js'),
  'rule--cancelled/16': () => import('@carbon/icons/es/rule--cancelled/16.js'),
  'rule--cancelled/24': () => import('@carbon/icons/es/rule--cancelled/24.js'),
  'save/16': () => import('@carbon/icons/es/save/16.js'),
  'save/24': () => import('@carbon/icons/es/save/24.js'),
  'screen/16': () => import('@carbon/icons/es/screen/16.js'),
  'screen/24': () => import('@carbon/icons/es/screen/24.js'),
  'script/16': () => import('@carbon/icons/es/script/16.js'),
  'script/24': () => import('@carbon/icons/es/script/24.js'),
  'search/16': () => import('@carbon/icons/es/search/16.js'),
  'search/24': () => import('@carbon/icons/es/search/24.js'),
  'security/16': () => import('@carbon/icons/es/security/16.js'),
  'security/24': () => import('@carbon/icons/es/security/24.js'),
  'send--alt/16': () => import('@carbon/icons/es/send--alt/16.js'),
  'send--alt/24': () => import('@carbon/icons/es/send--alt/24.js'),
  'service-id/16': () => import('@carbon/icons/es/service-id/16.js'),
  'service-id/24': () => import('@carbon/icons/es/service-id/24.js'),
  'settings/16': () => import('@carbon/icons/es/settings/16.js'),
  'settings/24': () => import('@carbon/icons/es/settings/24.js'),
  'share/16': () => import('@carbon/icons/es/share/16.js'),
  'share/24': () => import('@carbon/icons/es/share/24.js'),
  'shopping--bag/16': () => import('@carbon/icons/es/shopping--bag/16.js'),
  'shopping--bag/24': () => import('@carbon/icons/es/shopping--bag/24.js'),
  'shopping--cart/16': () => import('@carbon/icons/es/shopping--cart/16.js'),
  'shopping--cart/24': () => import('@carbon/icons/es/shopping--cart/24.js'),
  'shuffle/16': () => import('@carbon/icons/es/shuffle/16.js'),
  'shuffle/24': () => import('@carbon/icons/es/shuffle/24.js'),
  'side-panel--close/16': () =>
    import('@carbon/icons/es/side-panel--close/16.js'),
  'side-panel--close/24': () =>
    import('@carbon/icons/es/side-panel--close/24.js'),
  'side-panel--open/16': () =>
    import('@carbon/icons/es/side-panel--open/16.js'),
  'side-panel--open/24': () =>
    import('@carbon/icons/es/side-panel--open/24.js'),
  'skip--back/16': () => import('@carbon/icons/es/skip--back/16.js'),
  'skip--back/24': () => import('@carbon/icons/es/skip--back/24.js'),
  'skip--forward/16': () => import('@carbon/icons/es/skip--forward/16.js'),
  'skip--forward/24': () => import('@carbon/icons/es/skip--forward/24.js'),
  'sort--ascending/16': () => import('@carbon/icons/es/sort--ascending/16.js'),
  'sort--ascending/24': () => import('@carbon/icons/es/sort--ascending/24.js'),
  'sort--descending/16': () =>
    import('@carbon/icons/es/sort--descending/16.js'),
  'sort--descending/24': () =>
    import('@carbon/icons/es/sort--descending/24.js'),
  'square--outline/16': () => import('@carbon/icons/es/square--outline/16.js'),
  'square--outline/24': () => import('@carbon/icons/es/square--outline/24.js'),
  'square--solid/16': () => import('@carbon/icons/es/square--solid/16.js'),
  'square--solid/24': () => import('@carbon/icons/es/square--solid/24.js'),
  'star/16': () => import('@carbon/icons/es/star/16.js'),
  'star/24': () => import('@carbon/icons/es/star/24.js'),
  'star--filled/16': () => import('@carbon/icons/es/star--filled/16.js'),
  'star--filled/24': () => import('@carbon/icons/es/star--filled/24.js'),
  'stop--outline/16': () => import('@carbon/icons/es/stop--outline/16.js'),
  'stop--outline/24': () => import('@carbon/icons/es/stop--outline/24.js'),
  'stop-sign/16': () => import('@carbon/icons/es/stop-sign/16.js'),
  'stop-sign/24': () => import('@carbon/icons/es/stop-sign/24.js'),
  'subtract/16': () => import('@carbon/icons/es/subtract/16.js'),
  'subtract/24': () => import('@carbon/icons/es/subtract/24.js'),
  'subtract--alt/16': () => import('@carbon/icons/es/subtract--alt/16.js'),
  'subtract--alt/24': () => import('@carbon/icons/es/subtract--alt/24.js'),
  'subtract--filled/16': () =>
    import('@carbon/icons/es/subtract--filled/16.js'),
  'subtract--filled/24': () =>
    import('@carbon/icons/es/subtract--filled/24.js'),
  'sun/16': () => import('@carbon/icons/es/sun/16.js'),
  'sun/24': () => import('@carbon/icons/es/sun/24.js'),
  'switcher/16': () => import('@carbon/icons/es/switcher/16.js'),
  'switcher/24': () => import('@carbon/icons/es/switcher/24.js'),
  'tablet--landscape/16': () =>
    import('@carbon/icons/es/tablet--landscape/16.js'),
  'tablet--landscape/24': () =>
    import('@carbon/icons/es/tablet--landscape/24.js'),
  'tag/16': () => import('@carbon/icons/es/tag/16.js'),
  'tag/24': () => import('@carbon/icons/es/tag/24.js'),
  'task--complete/16': () => import('@carbon/icons/es/task--complete/16.js'),
  'task--complete/24': () => import('@carbon/icons/es/task--complete/24.js'),
  'task--remove/16': () => import('@carbon/icons/es/task--remove/16.js'),
  'task--remove/24': () => import('@carbon/icons/es/task--remove/24.js'),
  'template/16': () => import('@carbon/icons/es/template/16.js'),
  'template/24': () => import('@carbon/icons/es/template/24.js'),
  'terminal/16': () => import('@carbon/icons/es/terminal/16.js'),
  'terminal/24': () => import('@carbon/icons/es/terminal/24.js'),
  'text--align--center/16': () =>
    import('@carbon/icons/es/text--align--center/16.js'),
  'text--align--center/24': () =>
    import('@carbon/icons/es/text--align--center/24.js'),
  'text--align--justify/16': () =>
    import('@carbon/icons/es/text--align--justify/16.js'),
  'text--align--justify/24': () =>
    import('@carbon/icons/es/text--align--justify/24.js'),
  'text--align--left/16': () =>
    import('@carbon/icons/es/text--align--left/16.js'),
  'text--align--left/24': () =>
    import('@carbon/icons/es/text--align--left/24.js'),
  'text--align--right/16': () =>
    import('@carbon/icons/es/text--align--right/16.js'),
  'text--align--right/24': () =>
    import('@carbon/icons/es/text--align--right/24.js'),
  'text--scale/16': () => import('@carbon/icons/es/text--scale/16.js'),
  'text--scale/24': () => import('@carbon/icons/es/text--scale/24.js'),
  'thumbnail--2/16': () => import('@carbon/icons/es/thumbnail--2/16.js'),
  'thumbnail--2/24': () => import('@carbon/icons/es/thumbnail--2/24.js'),
  'thumbs-down/16': () => import('@carbon/icons/es/thumbs-down/16.js'),
  'thumbs-down/24': () => import('@carbon/icons/es/thumbs-down/24.js'),
  'thumbs-up/16': () => import('@carbon/icons/es/thumbs-up/16.js'),
  'thumbs-up/24': () => import('@carbon/icons/es/thumbs-up/24.js'),
  'time/16': () => import('@carbon/icons/es/time/16.js'),
  'time/24': () => import('@carbon/icons/es/time/24.js'),
  'time--filled/16': () => import('@carbon/icons/es/time--filled/16.js'),
  'time--filled/24': () => import('@carbon/icons/es/time--filled/24.js'),
  'tool-box/16': () => import('@carbon/icons/es/tool-box/16.js'),
  'tool-box/24': () => import('@carbon/icons/es/tool-box/24.js'),
  'tools/16': () => import('@carbon/icons/es/tools/16.js'),
  'tools/24': () => import('@carbon/icons/es/tools/24.js'),
  'trash-can/16': () => import('@carbon/icons/es/trash-can/16.js'),
  'trash-can/24': () => import('@carbon/icons/es/trash-can/24.js'),
  'triangle--outline/16': () =>
    import('@carbon/icons/es/triangle--outline/16.js'),
  'triangle--outline/24': () =>
    import('@carbon/icons/es/triangle--outline/24.js'),
  'triangle--solid/16': () => import('@carbon/icons/es/triangle--solid/16.js'),
  'triangle--solid/24': () => import('@carbon/icons/es/triangle--solid/24.js'),
  'unlocked/16': () => import('@carbon/icons/es/unlocked/16.js'),
  'unlocked/24': () => import('@carbon/icons/es/unlocked/24.js'),
  'up-to-top/16': () => import('@carbon/icons/es/up-to-top/16.js'),
  'up-to-top/24': () => import('@carbon/icons/es/up-to-top/24.js'),
  'upload/16': () => import('@carbon/icons/es/upload/16.js'),
  'upload/24': () => import('@carbon/icons/es/upload/24.js'),
  'user/16': () => import('@carbon/icons/es/user/16.js'),
  'user/24': () => import('@carbon/icons/es/user/24.js'),
  'user--admin/16': () => import('@carbon/icons/es/user--admin/16.js'),
  'user--admin/24': () => import('@carbon/icons/es/user--admin/24.js'),
  'user--avatar/16': () => import('@carbon/icons/es/user--avatar/16.js'),
  'user--avatar/24': () => import('@carbon/icons/es/user--avatar/24.js'),
  'user--avatar--filled/16': () =>
    import('@carbon/icons/es/user--avatar--filled/16.js'),
  'user--avatar--filled/24': () =>
    import('@carbon/icons/es/user--avatar--filled/24.js'),
  'user--follow/16': () => import('@carbon/icons/es/user--follow/16.js'),
  'user--follow/24': () => import('@carbon/icons/es/user--follow/24.js'),
  'user--multiple/16': () => import('@carbon/icons/es/user--multiple/16.js'),
  'user--multiple/24': () => import('@carbon/icons/es/user--multiple/24.js'),
  'video/16': () => import('@carbon/icons/es/video/16.js'),
  'video/24': () => import('@carbon/icons/es/video/24.js'),
  'video--off/16': () => import('@carbon/icons/es/video--off/16.js'),
  'video--off/24': () => import('@carbon/icons/es/video--off/24.js'),
  'view/16': () => import('@carbon/icons/es/view/16.js'),
  'view/24': () => import('@carbon/icons/es/view/24.js'),
  'view--off/16': () => import('@carbon/icons/es/view--off/16.js'),
  'view--off/24': () => import('@carbon/icons/es/view--off/24.js'),
  'virtual-private-cloud/16': () =>
    import('@carbon/icons/es/virtual-private-cloud/16.js'),
  'virtual-private-cloud/24': () =>
    import('@carbon/icons/es/virtual-private-cloud/24.js'),
  'vlan/16': () => import('@carbon/icons/es/vlan/16.js'),
  'vlan/24': () => import('@carbon/icons/es/vlan/24.js'),
  'vmdk-disk/16': () => import('@carbon/icons/es/vmdk-disk/16.js'),
  'vmdk-disk/24': () => import('@carbon/icons/es/vmdk-disk/24.js'),
  'volume--down/16': () => import('@carbon/icons/es/volume--down/16.js'),
  'volume--down/24': () => import('@carbon/icons/es/volume--down/24.js'),
  'volume--mute/16': () => import('@carbon/icons/es/volume--mute/16.js'),
  'volume--mute/24': () => import('@carbon/icons/es/volume--mute/24.js'),
  'volume--up/16': () => import('@carbon/icons/es/volume--up/16.js'),
  'volume--up/24': () => import('@carbon/icons/es/volume--up/24.js'),
  'warning/16': () => import('@carbon/icons/es/warning/16.js'),
  'warning/24': () => import('@carbon/icons/es/warning/24.js'),
  'warning--alt/16': () => import('@carbon/icons/es/warning--alt/16.js'),
  'warning--alt/24': () => import('@carbon/icons/es/warning--alt/24.js'),
  'warning--alt--filled/16': () =>
    import('@carbon/icons/es/warning--alt--filled/16.js'),
  'warning--alt--filled/24': () =>
    import('@carbon/icons/es/warning--alt--filled/24.js'),
  'warning--diamond/16': () =>
    import('@carbon/icons/es/warning--diamond/16.js'),
  'warning--diamond/24': () =>
    import('@carbon/icons/es/warning--diamond/24.js'),
  'warning--filled/16': () => import('@carbon/icons/es/warning--filled/16.js'),
  'warning--filled/24': () => import('@carbon/icons/es/warning--filled/24.js'),
  'warning--hex/16': () => import('@carbon/icons/es/warning--hex/16.js'),
  'warning--hex/24': () => import('@carbon/icons/es/warning--hex/24.js'),
  'warning--hex--filled/16': () =>
    import('@carbon/icons/es/warning--hex--filled/16.js'),
  'warning--hex--filled/24': () =>
    import('@carbon/icons/es/warning--hex--filled/24.js'),
  'watch/16': () => import('@carbon/icons/es/watch/16.js'),
  'watch/24': () => import('@carbon/icons/es/watch/24.js'),
  'webhook/16': () => import('@carbon/icons/es/webhook/16.js'),
  'webhook/24': () => import('@carbon/icons/es/webhook/24.js'),
  'wifi/16': () => import('@carbon/icons/es/wifi/16.js'),
  'wifi/24': () => import('@carbon/icons/es/wifi/24.js'),
  'wifi--off/16': () => import('@carbon/icons/es/wifi--off/16.js'),
  'wifi--off/24': () => import('@carbon/icons/es/wifi--off/24.js'),
  'wikis/16': () => import('@carbon/icons/es/wikis/16.js'),
  'wikis/24': () => import('@carbon/icons/es/wikis/24.js'),
  'zoom--in/16': () => import('@carbon/icons/es/zoom--in/16.js'),
  'zoom--in/24': () => import('@carbon/icons/es/zoom--in/24.js'),
  'zoom--out/16': () => import('@carbon/icons/es/zoom--out/16.js'),
  'zoom--out/24': () => import('@carbon/icons/es/zoom--out/24.js'),
};
