export const HDS_CODE_BLOCK_LINE_HIGHLIGHT = 'rgba(0, 74, 222, 0.2)';
export const HDS_CODE_BLOCK_LINE_HIGHLIGHT_BORDER = '#1b5fe5';
export const HDS_CODE_BLOCK_WHITE = '#efeff1';

export const HDS_CODE_EDITOR_COLOR_FOREGROUND_PRIMARY = '#d5d7db';
export const HDS_CODE_EDITOR_COLOR_FOREGROUND_FAINT = '#878a8f';
export const HDS_CODE_EDITOR_COLOR_FOREGROUND_HIGH_CONTRAST = '#ffffff';
export const HDS_CODE_EDITOR_COLOR_SURFACE_FAINT = '#15181e';
