/**
 * Copyright IBM Corp. 2021, 2025
 * SPDX-License-Identifier: MPL-2.0
 */

export const HDS_CODE_BLOCK_WHITE = '#efeff1';
export const HDS_CODE_BLOCK_BLUE = '#2d8eff';
export const HDS_CODE_BLOCK_GREEN = '#86ff13';
export const HDS_CODE_BLOCK_ORANGE = '#ffa800';
export const HDS_CODE_BLOCK_PURPLE = '#c76cff';
export const HDS_CODE_BLOCK_RED = '#ff3b20';
export const HDS_CODE_BLOCK_CYAN = '#32fff7';

export const HDS_CODE_BLOCK_LINE_HIGHLIGHT = 'rgba(0, 74, 222, 0.2)';
export const HDS_CODE_BLOCK_LINE_HIGHLIGHT_BORDER = '#1b5fe5';

export const HDS_CODE_EDITOR_COLOR_FOREGROUND_PRIMARY = '#d5d7db';
export const HDS_CODE_EDITOR_COLOR_FOREGROUND_FAINT = '#878a8f';
export const HDS_CODE_EDITOR_COLOR_FOREGROUND_CRITICAL = '#EF3016';

export const HDS_CODE_EDITOR_COLOR_SURFACE_PRIMARY = '#0D0E12';
export const HDS_CODE_EDITOR_COLOR_SURFACE_FAINT = '#15181e';
export const HDS_CODE_EDITOR_COLOR_SURFACE_INTERACTIVE_ACTIVE = '#2B303C';
export const HDS_CODE_EDITOR_COLOR_FOCUS_ACTION_INTERNAL = '#9BC7FD';
export const HDS_CODE_EDITOR_COLOR_FOCUS_ACTION_EXTERNAL = '#0D69F2';
