/**
 * Copyright IBM Corp. 2021, 2025
 * SPDX-License-Identifier: MPL-2.0
 */

import fs from 'fs-extra';

// @ts-ignore svgstore doesn't have type definitions available
import svgstore from 'svgstore';

import { ConfigData } from '../@types/ConfigData';
import { AssetsCatalog } from '../@types/AssetsCatalog';
import replaceDynamicColor from './replaceDynamicColor';

export async function generateBundleSVGSprite({ config, catalog } : { config: ConfigData, catalog: AssetsCatalog }): Promise<void> {

    const tempSVGFolderPath = config.tempFolder;

    // remove the generated content from the destination folder
    try {
        await fs.emptyDir(`${config.mainFolder}/svg-sprite`)
    } catch (err) {
        console.error(err);
    }

    // generate the sprite via "svgstore"
    const sprites = svgstore({
        // see https://github.com/svgstore/svgstore#options for details
        renameDefs: false, // we already create unique IDs (using the icon name) in the SVGO step
        svgAttrs: { 
            width: '0',
            height: '0',
            // some browsers will not correctly render remote <use> references unless the remote document has the correct namespace
            xmlns: "http://www.w3.org/2000/svg",
            // Next.js expects there to be a viewBox attribute to calculate dimensions; while this isn't actually useful in the case of an SVG sprite, it does prevent Next.js from throwing an error about being unable to parse the file
            viewBox: "0 0 0 0",
            class: 'flight-sprite-container',
            'aria-hidden': 'true'
        },
    });

    // add the SVGs to the sprite
    for(const { fileName } of catalog.assets) {
        let svgSource = await fs.readFile(`${tempSVGFolderPath}/${fileName}.svg`, 'utf8');
        svgSource = replaceDynamicColor(svgSource);
        // add the processed SVG content to the sprite (notice: the first argument is the symbol ID)
        sprites.add(`flight-${fileName}`, svgSource);
    }

    // transform the "sprite" into a string
    // see https://github.com/svgstore/svgstore#tostringoptions-string
    const svgSpriteContent = sprites.toString({ inline: true });

    let svgModuleContent = '/**\n * Copyright IBM Corp. 2021, 2025\n * SPDX-License-Identifier: MPL-2.0\n */\n\n';
    svgModuleContent += '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n';
    svgModuleContent += `module.exports = '${svgSpriteContent}';\n`;

    // update the SVG "module"
    await fs.writeFile(`${config.mainFolder}/svg-sprite/svg-sprite-module.js`, svgModuleContent);

    let svgFileContent = '<!--\n * Copyright IBM Corp. 2021, 2025\n * SPDX-License-Identifier: MPL-2.0\n-->\n\n';
    svgFileContent += '<!-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. -->\n';
    svgFileContent += `${svgSpriteContent}\n`;

    // update the SVG file
    await fs.writeFile(`${config.mainFolder}/svg-sprite/svg-sprite.svg`, svgFileContent);
}
