import fs from 'fs-extra';
import chalk from 'chalk';

import { ConfigData } from '../@types/ConfigData';
import { AssetsCatalog } from '../@types/AssetsCatalog';

// see https://codepen.io/tigt/post/optimizing-svgs-in-data-uris
import svgToMiniDataURI from 'mini-svg-data-uri';

export async function generateBundleCSS({ config, catalog }: { config: ConfigData, catalog: AssetsCatalog }): Promise<void> {

    // TODO add better logging
    console.log('generateBundleCSS');

    const tempSVGFolderPath = `${config.buildDistFolder}/temp`;
    const distBundleFolderPath = `${config.buildDistFolder}/flight-icons-css`;

    // create the destination folder
    fs.mkdirs(distBundleFolderPath);

    // copy the assets catalog file
    fs.copy(`${config.syncOutputFolder}/catalog.json`, `${distBundleFolderPath}/catalog.json`);


    let cssContentBackground = '/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */\n';
    let cssContentCustomProp = '/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */\n';
    let scssContentForConsul = '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n';

    for (const { fileName } of catalog.assets) {

        // get the optimized SVG and urlencode it
        const svgOptimized = await fs.readFile(`${tempSVGFolderPath}/${fileName}.svg`, 'utf8');
        const svgUrlEncoded = svgToMiniDataURI(svgOptimized);

        // add an entry to each CSS file
        const urlDataImage = `url("data:image/svg+xml;utf8,${svgUrlEncoded}")`
        cssContentBackground += `.flight-icon-${fileName} { background-image: ${urlDataImage}; }\n`;
        cssContentCustomProp += `.flight-icon-${fileName} { --flight-icon-data-image: ${urlDataImage}; }\n`;
        scssContentForConsul += `\n%flight-icon-${fileName}-prop { --flight-icon-${fileName}: ${urlDataImage}; }\n`;
        scssContentForConsul += `%with-flight-icon-${fileName}-icon {\n`;
        scssContentForConsul += `    @extend %with-icon, %flight-icon-${fileName}-prop !optional;\n`;
        scssContentForConsul += `    background-image: $flight-icon-${fileName};\n`;
        scssContentForConsul += `} \n`;
        scssContentForConsul += `%with-flight-icon-${fileName}-mask {\n`;
        scssContentForConsul += `    @extend %with-mask, %flight-icon-${fileName}-prop !optional;\n`;
        scssContentForConsul += `    -webkit-mask-image: $flight-icon-${fileName};\n`;
        scssContentForConsul += `    mask-image: $flight-icon-${fileName}-svg;\n`;
        scssContentForConsul += `} \n`;
    }

    // save the CSS files in the destination folder
    await fs.writeFile(`${distBundleFolderPath}/flight-icons-background.css`, cssContentBackground);
    await fs.writeFile(`${distBundleFolderPath}/flight-icons-customprop.css`, cssContentCustomProp);
    await fs.writeFile(`${distBundleFolderPath}/flight-icons-forconsul.scss`, scssContentForConsul);

    // TODO something else?
}