name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
      with:
        # Token setup in hashibot-hds' account
        repo-token: "${{ secrets.PAT_TOKEN }}"
        sync-labels: true